#!/bin/bash

echo "🔧 URGENT: Your .env.local file needs these exact changes:"
echo "================================================================"
echo ""
echo "📝 STEP 1: ADD this missing line anywhere in your .env.local:"
echo "WHATSAPP_WABA_ID=596136450071721"
echo ""
echo "📝 STEP 2: FIND this line in your .env.local:"
echo "WHATSAPP_ACCESS_TOKEN=EAANi75PUoDwBO3om7CwCZA7R5IJx2PouQxQgmECFSBVjGdGFK3WXUD3jpDflpvtZAjoAwFG8VZB4R27AiRKU4..."
echo ""
echo "📝 STEP 2: CHANGE it to:"
echo "WHATSAPP_SYSTEM_USER_TOKEN=EAANi75PUoDwBO3om7CwCZA7R5IJx2PouQxQgmECFSBVjGdGFK3WXUD3jpDflpvtZAjoAwFG8VZB4R27AiRKU4..."
echo ""
echo "📝 STEP 3: FIND this line in your .env.local:"
echo "WHATSAPP_PHONE_NUMBER_ID=+15556296578"
echo ""
echo "📝 STEP 3: CHANGE it to:"
echo "WHATSAPP_PHONE_NUMBER_ID=564943553373191"
echo ""
echo "🚀 STEP 4: Save the file and restart your server: npm run dev"
echo ""
echo "================================================================"
echo "❌ Current configuration in your .env.local:"
echo "================================================================"
grep "WHATSAPP" .env.local
echo ""
echo "================================================================"
echo "✅ What it should look like after changes:"
echo "================================================================"
echo "WHATSAPP_WABA_ID=596136450071721"
echo "WHATSAPP_PHONE_NUMBER_ID=564943553373191"
echo "WHATSAPP_SYSTEM_USER_TOKEN=EAANi75PUoDwBO3om7CwCZA7R5IJx2PouQxQgmECFSBVjGdGFK3WXUD3jpDflpvtZAjoAwFG8VZB4R27AiRKU4shxWkomjWZCSZC90CxXKiEOgx1jwj94PLa5ZCHYg1tbbMlZCSXp7kkKKaGUhBy2F7pg3cxPiore2OKm3E21jrgCLDVZAUfYXKvjrOzmHd78Ejf22I21QaRNZAYtmn8aWcKKET0NFcCMjIGCEYtYzvtjl"
echo "WHATSAPP_VERIFY_TOKEN=zenrent5512429"
echo "" 