-- Create initial properties
INSERT INTO properties (
  id,
  user_id,
  property_code,
  address,
  city,
  postcode,
  property_type,
  bedrooms,
  bathrooms,
  is_furnished,
  purchase_date,
  purchase_price,
  current_valuation,
  description,
  status,
  photo_url,
  energy_rating,
  council_tax_band,
  has_garden,
  has_parking,
  gas_safety_expiry,
  electrical_safety_expiry,
  notes,
  metadata,
  created_at,
  updated_at
) VALUES 
(
  '7a2e1487-f17b-4ceb-b6d1-56934589025b',
  'b85371f5-2ec6-4ceb-9526-51a60d19fcc2',
  'prop_15_crescent_road',
  '15 Crescent Road',
  'London',
  'SW11 5PL',
  'flat',
  2,
  1,
  true,
  '2020-06-15',
  380000,
  450000,
  'Modern apartment in prime London location with excellent transport links. Recently renovated with high-end finishes.',
  'active',
  'https://example.com/properties/15-crescent-road.jpg',
  'B',
  'D',
  false,
  true,
  NOW() + INTERVAL '6 months',
  NOW() + INTERVAL '4 years',
  'Prime location property with strong rental demand',
  '{"amenities": ["Central Heating", "Double Glazing", "Fitted Kitchen", "Garden Access", "Bike Storage"], "year_built": 2005, "square_footage": 850}',
  NOW() - INTERVAL '3 years',
  NOW()
),
(
  'bd8e3211-2403-47ac-9947-7a4842c5a4e3',
  'b85371f5-2ec6-4ceb-9526-51a60d19fcc2',
  'prop_42_harley_street',
  '42 Harley Street',
  'London',
  'W1G 8PR',
  'house',
  3,
  2,
  true,
  '2019-03-20',
  320000,
  380000,
  'Spacious family home in quiet residential area. Features a large garden and modern kitchen.',
  'active',
  'https://example.com/properties/42-harley-street.jpg',
  'C',
  'C',
  true,
  true,
  NOW() + INTERVAL '8 months',
  NOW() + INTERVAL '3 years',
  'Well-maintained property with long-term tenants',
  '{"amenities": ["Garden", "Central Heating", "Double Glazing", "Off-Street Parking", "Conservatory"], "year_built": 1998, "square_footage": 1200}',
  NOW() - INTERVAL '4 years',
  NOW()
),
(
  'dfe98af6-7b35-4eb1-a75d-b9cb279d86d8',
  'b85371f5-2ec6-4ceb-9526-51a60d19fcc2',
  'prop_8_victoria_gardens',
  '8 Victoria Gardens',
  'Manchester',
  'M4 7DJ',
  'house',
  4,
  3,
  true,
  '2021-09-10',
  450000,
  520000,
  'Luxurious detached house with modern amenities and excellent schools nearby. Recently refurbished throughout.',
  'active',
  'https://example.com/properties/8-victoria-gardens.jpg',
  'A',
  'E',
  true,
  true,
  NOW() + INTERVAL '10 months',
  NOW() + INTERVAL '4 years',
  'High-end property with premium fixtures and fittings',
  '{"amenities": ["Garden", "Central Heating", "Double Glazing", "Garage", "Home Office", "Smart Home System"], "year_built": 2010, "square_footage": 1800}',
  NOW() - INTERVAL '2 years',
  NOW()
); 